-- Add guest_session_id to kds_orders for multi-device QR sessions
-- Apply manually in Supabase SQL Editor against the kds_orders table.
--
-- Anonymous device UUID (opaque string, ≤ 64 chars) generated by the
-- MenuBuilder QR cart client. Nullable: legacy rows and non-QR sources
-- (manual POS, phone takeaway) will not supply a value. Partial index
-- keeps lookups by session_id cheap without bloat on legacy rows.

ALTER TABLE kds_orders
  ADD COLUMN IF NOT EXISTS guest_session_id text NULL;

CREATE INDEX IF NOT EXISTS kds_orders_guest_session_id_idx
  ON kds_orders (guest_session_id)
  WHERE guest_session_id IS NOT NULL;
